# Enable pycodestyle (`E`, `W`), Pyflakes (`F`), pyupgrade (`UP`)
# McCabe complexity (`C901`), isort (`I`) codes by default.
lint.select = ["E", "F", "W", "C901", "I", "UP"]
lint.ignore = ["E501"]

# Allow fix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
