version: '3'

tasks:

  linter:
    desc: Run ruff linter and fix the suggested changes for the codebase
    dir: '{{ .USER_WORKING_DIR }}'
    vars:
      SRC_DIR:
        sh: if [ -d "src" ]; then echo src; else echo app; fi
    cmds:
      - uv run ruff check . --fix --verbose --config "src=['.', '{{ .SRC_DIR }}']"

  formatter:
    desc: Run ruff formatter to clean up the codebase
    dir: '{{ .USER_WORKING_DIR }}'
    cmds:
      - uv run ruff format . --verbose
